### ISSUE TITLE
GrahamCampbell\Manager\ManagerInterface::getConnectionConfig($name) error

### ISSUE THREAD

**Issue by toddvalentine** [BKWLD/decoy#83]
Have begun seeing the following error:

Declaration of Bkwld\Upchuck\Manager::getConnectionConfig(string $name = NULL) must be compatible with GrahamCampbell\Manager\ManagerInterface::getConnectionConfig($name)

**Comment by weotch** [comment]
This is fixed by https://github.com/BKWLD/upchuck/commit/4cbe4cb752672f681deb8116a503d11257f6be1b and tagged in Uphuck 2.2.1.  Can you update your Upchuck dependency to this and see if it fixes it?

**Comment by jacobrossdev** [comment]
I updated from 2.4.1 to 2.5.0 after seeing this thread and I am still having this issue with registering new users.

**Comment by weotch** [comment]
Very weird.  Can you check your composer.lock file and see what version of `graham-campbell/manager` you've installed?

**Comment by jacobrossdev** [comment]
I have version 2.5 installed.

**Comment by weotch** [comment]
I think that's the problem then ... Upchuck is expecting you to be on 3.0 of `graham-campbell/manager` ... I should update it's version constraints accordingly.

Can you update to 3.0?

**Comment by jacobrossdev** [comment]
Does `composer require graham-campbell/manager` not do the trick?

**Comment by jacobrossdev** [comment]
I tried `composer require graham-campbell/manager` and I tried changing the version in composer.json along with `composer update` and I am not getting a more up-to-date version. Do I need to manually download?

**Comment by toddvalentine** [comment]
been awhile since I created this, but I think I recall a dependency requiring php7 and I was on 5.6?

**Comment by jacobrossdev** [comment]
I updated to PHP7 and before graham-campbell/manager was able to update to 3.0, it seems that there are some other dependencies that are not compatible. Here's the response I got from my terminal

`  Problem 1
    - graham-campbell/flysystem v3.7.0 requires graham-campbell/manager ^2.3 -> satisfiable by graham-campbell/manager[v2.3.0, v2.3.1, v2.4.0, v2.5.0] but these conflict with your requirements or minimum-stability.
    - graham-campbell/flysystem v3.7.0 requires graham-campbell/manager ^2.3 -> satisfiable by graham-campbell/manager[v2.3.0, v2.3.1, v2.4.0, v2.5.0] but these conflict with your requirements or minimum-stability.
    - graham-campbell/flysystem v3.7.0 requires graham-campbell/manager ^2.3 -> satisfiable by graham-campbell/manager[v2.3.0, v2.3.1, v2.4.0, v2.5.0] but these conflict with your requirements or minimum-stability.
    - Installation request for graham-campbell/flysystem (locked at v3.7.0) -> satisfiable by graham-campbell/flysystem[v3.7.0].
`
